[project]
name = "ydlx"
version = "0.1.1"
description = "An interactive, feature-rich CLI dashboard and downloader for yt-dlp"
readme = "README.md"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
requires-python = ">=3.11"
dependencies = [
    "typer>=0.26.8",
    "yt-dlp>=2026.7.4",
    "rich>=13.7.0",
    "curl-cffi>=0.7.0",
]

authors = [{ name = "Yousef Rashad", email = "yousefmrashad@proton.me" }]

[project.urls]
Homepage = "https://github.com/yousefmrashad/ydlx"
Repository = "https://github.com/yousefmrashad/ydlx"
Issues = "https://github.com/yousefmrashad/ydlx/issues"

[project.scripts]
ydlx = "ydlx:app"

[build-system]
requires = ["setuptools>=77.0.0"]
build-backend = "setuptools.build_meta"

[tool.uv]
package = true

[tool.basedpyright]
typeCheckingMode = "standard"
venvPath = "."
venv = ".venv"
pythonVersion = "3.11"
exclude = [
    "build",
    ".venv",
]
